-- Alarm occurrence history (Dismissed / Snoozed / Missed), scoped per user.
-- Apply in Supabase SQL editor or via migration tooling.

CREATE TABLE IF NOT EXISTS public.alarm_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    alarm_id bigint REFERENCES public.alarms (id) ON DELETE SET NULL,
    label text NOT NULL DEFAULT '',
    category text NOT NULL DEFAULT '',
    scheduled_fire_at timestamptz NOT NULL,
    status text NOT NULL CHECK (status IN ('missed', 'dismissed', 'snoozed')),
    action_at timestamptz,
    snooze_minutes integer CHECK (snooze_minutes IS NULL OR snooze_minutes >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT alarm_history_event_unique UNIQUE (user_id, alarm_id, scheduled_fire_at)
);

CREATE INDEX IF NOT EXISTS alarm_history_user_scheduled_idx
    ON public.alarm_history (user_id, scheduled_fire_at DESC);

COMMENT ON TABLE public.alarm_history IS 'Per-fire alarm outcomes for History; merge key is user + alarm + scheduled_fire_at.';
